# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a11d2c943737a2b5e8d1e8c4b22d0df072dc858a96f99a2810453c30277ec1fe2e12e6dec7f55d918a5b806c4281f4fd6aea19d0e22e6b4effdbced2a4393d3

test:
  secret_key_base: e55d43377071587a9046a77879e2ed14a5df4fdd0854f1859df1c6b9068b3d94bce413350591ed5f6d6f9e4ac90279264e0e710f8c3496a5f8f29a22ad0995d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
